insert into tb_artista (nome) values ('Death');
insert into tb_artista (nome) values ('Morbid Angel');
insert into tb_artista (nome) values ('Cannibal Corpse');
insert into tb_artista (nome) values ('Deicide');
insert into tb_artista (nome) values ('Obituary');
insert into tb_artista (nome) values ('Entombed');
insert into tb_artista (nome) values ('Dismember');
insert into tb_artista (nome) values ('At The Gates');
insert into tb_artista (nome) values ('Carcass');
insert into tb_artista (nome) values ('Bolt Thrower');
insert into tb_artista (nome) values ('Slayer');
insert into tb_artista (nome) values ('Kreator');
insert into tb_artista (nome) values ('Exodus');
insert into tb_artista (nome) values ('Testament');
insert into tb_artista (nome) values ('Sepultura');
insert into tb_artista (nome) values ('Sodom');
insert into tb_artista (nome) values ('Destruction');
insert into tb_artista (nome) values ('Overkill');
insert into tb_artista (nome) values ('Anthrax');
insert into tb_artista (nome) values ('Municipal Waste');
insert into tb_artista (nome) values ('Mayhem');
insert into tb_artista (nome) values ('Darkthrone');
insert into tb_artista (nome) values ('Burzum');
insert into tb_artista (nome) values ('Immortal');
insert into tb_artista (nome) values ('Emperor');
insert into tb_artista (nome) values ('Gorgoroth');
insert into tb_artista (nome) values ('Behemoth');
insert into tb_artista (nome) values ('Marduk');
insert into tb_artista (nome) values ('Watain');
insert into tb_artista (nome) values ('Satyricon');
insert into tb_artista (nome) values ('Ministry');
insert into tb_artista (nome) values ('Nine Inch Nails');
insert into tb_artista (nome) values ('Rammstein');
insert into tb_artista (nome) values ('Fear Factory');
insert into tb_artista (nome) values ('Godflesh');
insert into tb_artista (nome) values ('KMFDM');
insert into tb_artista (nome) values ('Skinny Puppy');
insert into tb_artista (nome) values ('Static-X');
insert into tb_artista (nome) values ('Rob Zombie');
insert into tb_artista (nome) values ('Marilyn Manson');
insert into tb_artista (nome) values ('Metallica');
insert into tb_artista (nome) values ('Megadeth');
insert into tb_artista (nome) values ('Pantera');
insert into tb_artista (nome) values ('Machine Head');
insert into tb_artista (nome) values ('Lamb of God');
insert into tb_artista (nome) values ('Gojira');
insert into tb_artista (nome) values ('Meshuggah');
insert into tb_artista (nome) values ('Opeth');
insert into tb_artista (nome) values ('Tool');
insert into tb_artista (nome) values ('Korn');
insert into tb_artista (nome) values ('Napalm Death');
insert into tb_artista (nome) values ('Arch Enemy');
insert into tb_artista (nome) values ('Amon Amarth');
insert into tb_artista (nome) values ('In Flames');
insert into tb_artista (nome) values ('Children of Bodom');
insert into tb_artista (nome) values ('Dying Fetus');
insert into tb_artista (nome) values ('Hypocrisy');
insert into tb_artista (nome) values ('Bloodbath');
insert into tb_artista (nome) values ('Rotting Christ');
insert into tb_artista (nome) values ('Mgla');
insert into tb_artista (nome) values ('Rata Blanca');
insert into tb_artista (nome) values ('Hermetica');
insert into tb_artista (nome) values ('V8');
insert into tb_artista (nome) values ('Horcas');
insert into tb_artista (nome) values ('Malon');
insert into tb_artista (nome) values ('Almafuerte');
insert into tb_artista (nome) values ('A.N.I.M.A.L');
insert into tb_artista (nome) values ('Brujeria');
insert into tb_artista (nome) values ('Saratoga');
insert into tb_artista (nome) values ('WarCry');
insert into tb_artista (nome) values ('Mago de Oz');
insert into tb_artista (nome) values ('Tierra Santa');
insert into tb_artista (nome) values ('Avalanch');
insert into tb_artista (nome) values ('Leo Jimenez');
insert into tb_artista (nome) values ('Obus');
insert into tb_artista (nome) values ('Baron Rojo');
insert into tb_artista (nome) values ('Angeles del Infierno');
insert into tb_artista (nome) values ('Sober');
insert into tb_artista (nome) values ('Hamlet');
insert into tb_artista (nome) values ('Soziedad Alkoholika');
insert into tb_artista (nome) values ('Transmetal');
insert into tb_artista (nome) values ('Luzbel');
insert into tb_artista (nome) values ('Cemican');
insert into tb_artista (nome) values ('Agora');
insert into tb_artista (nome) values ('Leprosy');
insert into tb_artista (nome) values ('Masacre');
insert into tb_artista (nome) values ('Kraken');
insert into tb_artista (nome) values ('Ekhymosis');
insert into tb_artista (nome) values ('Nepentes');
insert into tb_artista (nome) values ('Internal Suffering');
insert into tb_artista (nome) values ('Puya');
insert into tb_artista (nome) values ('Resorte');
insert into tb_artista (nome) values ('Ill Nino');
insert into tb_artista (nome) values ('Los Brujos');
insert into tb_artista (nome) values ('Santa Sabina');
insert into tb_artista (nome) values ('Acidez');
insert into tb_artista (nome) values ('Zenobia');
insert into tb_artista (nome) values ('Saurom');
insert into tb_artista (nome) values ('Khymera');
insert into tb_artista (nome) values ('Dharma');
insert into tb_artista (nome) values ('Angkor');
insert into tb_artista (nome) values ('Anabantha');
insert into tb_artista (nome) values ('Catharsis');
insert into tb_artista (nome) values ('Haggard Latino');
insert into tb_artista (nome) values ('Inquisition Latino');
insert into tb_artista (nome) values ('Nervosa');
insert into tb_artista (nome) values ('Sepultura Roots Era');
insert into tb_artista (nome) values ('Cultura Tres');
insert into tb_artista (nome) values ('Alestorm');
insert into tb_artista (nome) values ('Running Wild');
insert into tb_artista (nome) values ('Swashbuckle');
insert into tb_artista (nome) values ('Ye Banished Privateers');
insert into tb_artista (nome) values ('Rumahoy');
insert into tb_artista (nome) values ('Storm Seeker');
insert into tb_artista (nome) values ('Visions of Atlantis');
insert into tb_artista (nome) values ('Blazon Stone');
insert into tb_artista (nome) values ('Red Rum');
insert into tb_artista (nome) values ('The Privateer');
insert into tb_artista (nome) values ('Pirate Hymn');
insert into tb_artista (nome) values ('Lagerstein');
insert into tb_artista (nome) values ('Fiddlers Green');
insert into tb_artista (nome) values ('Terra Atlantica');
insert into tb_artista (nome) values ('Drunken Rampage');
insert into tb_artista (nome) values ('Captain Black Beard');
insert into tb_artista (nome) values ('Stormfrun');
insert into tb_artista (nome) values ('Haggard Seas');
insert into tb_artista (nome) values ('Suidakra Seas');
insert into tb_artista (nome) values ('Northwind Wolves');
insert into tb_artista (nome) values ('Iron SeaWolf');
insert into tb_artista (nome) values ('Skull and Crossbones');
insert into tb_artista (nome) values ('Pirates Creed');
insert into tb_artista (nome) values ('Black Sails Metal');
insert into tb_artista (nome) values ('Rum Rebellion');
