services:
  postgres:
    image: postgres:15
    container_name: seplagmt_database
    restart: always
    environment:
      POSTGRES_DB: db_seplagmt_desenvolvimento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: